[package]
name = "interacto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
mockall = "0.11.4"
mockall_double = "0.3.0"
# s_test_fixture = "0.1.8"
